apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: peer-broker-a
spec:
  env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: amq-db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: amq-db-credentials
          key: password
  brokerProperties:
    - 'storeConfiguration=DATABASE'
    - 'storeConfiguration.jdbcDriverClassName=oracle.jdbc.OracleDriver'
    - |
      storeConfiguration.jdbcConnectionUrl=jdbc:oracle:thin:${DB_USERNAME}/${DB_PASSWORD}@oracle-database-service.oracle-db-amq.svc.cluster.local:1521/FREEPDB1