apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: amq-broker
spec:
  env:
    - name: JAVA_ARGS_APPEND
      value: "-Dwebconfig.bindings.artemis.uri=http://0.0.0.0:8161 -Dartemis.acceptors.amqp.host=0.0.0.0"
    - name: AMQ_EXTRA_ARGS
      value: "--relax-jolokia"
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
    image: placeholder
    persistenceEnabled: true
    journalType: aio
    messageMigration: true
    enableMetricsPlugin: true
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    storage:
      size: "4Gi"
  console:
    expose: true
  acceptors:
    - name: amqp-acceptor
      port: 5672
      protocols: 'CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE'
      expose: true
      sslEnabled: true
      sslSecret: amqp-acceptor-ptls
  brokerProperties:
    - "acceptorConfigurations.amqp-acceptor.params.sslAutoReload=true"
    - "# Enable auto-creation of queues"
    - addressSettings."#".autoCreateQueues=true
    - addressSettings."#".autoCreateAddresses=true
    - "# Configure default address settings"
    - addressSettings."#".defaultQueueRoutingType=ANYCAST
    - addressSettings."#".defaultAddressRoutingType=ANYCAST
    - "# Configure myQueue as anycast"
    - addressConfigurations."myQueue".routingTypes=ANYCAST
    - addressConfigurations."myQueue".queueConfigs."myQueue".routingType=ANYCAST
    - "# Configure DLQ settings"
    - addressSettings."myQueue".deadLetterAddress=DLQ
    - addressSettings."myQueue".expiryAddress=ExpiryQueue
    - addressSettings."myQueue".maxDeliveryAttempts=3
  resourceTemplates:
    - selector:
        kind: Service
        name: broker-amqp-acceptor-0-svc
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: amqp-acceptor-ptls